import Table from '@/components/Table'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Crud App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        {/* Parent App  */}
        <div>

            {/* Start Title */}
            <div>
              <h1 className='text-center capitalize font-medium text-xl lg:text-4xl mt-5'>employee management</h1>

              <div className='container mx-auto py-5 border-b'> 
                <div>
                  <button className='bg-slate-800 text-white rounded py-2 px-5'>Add Employee</button>
                </div>
              </div>
            </div>

        </div>
      
      </main>
    </>
  )
}
